Repository minetest-mods/mesecons, pull requests merged in 2018-12, with the labels that each got.

#442 Fix typos
  mesecons_fpga/doc/fpga/description.html
  mesecons_powerplant/doc/powerplant/description.html
  mesecons_pressureplates/doc/pressureplate_stone/description.html
  mesecons_pressureplates/doc/pressureplate_wood/description.html
  mesecons_random/doc/ghoststone/description.html
  mesecons_random/doc/removestone/description.html
  mesecons_solarpanel/doc/solarpanel/description.html
  mesecons_switch/doc/switch/description.html
Labels: documentation, trivial

#436 Make sticky piston stick falling things as well
  mesecons_pistons/init.lua
Labels: bugfix

#447 Document inactive block behaviour
  mesecons_blinkyplant/doc/blinkyplant/description.html
  mesecons_commandblock/doc/commandblock/description.html
  mesecons_delayer/doc/delayer/description.html
  mesecons_detector/doc/nodedetector/description.html
  mesecons_detector/doc/objectdetector/description.html
  mesecons_extrawires/doc/corner/description.html
  mesecons_extrawires/doc/crossing/description.html
  mesecons_extrawires/doc/mese/description.html
  mesecons_extrawires/doc/tjunction/description.html
  mesecons_extrawires/doc/vertical/description.html
  mesecons_fpga/doc/fpga/description.html
  mesecons_gates/doc/and/description.html
  mesecons_gates/doc/diode/description.html
  mesecons_gates/doc/nand/description.html
  mesecons_gates/doc/nor/description.html
  mesecons_gates/doc/not/description.html
  mesecons_gates/doc/or/description.html
  mesecons_gates/doc/xor/description.html
  mesecons_hydroturbine/doc/waterturbine/description.html
  mesecons_insulated/doc/insulated/description.html
  mesecons_lightstone/doc/lightstone_blue/description.html
  mesecons_lightstone/doc/lightstone_darkgrey/description.html
  mesecons_lightstone/doc/lightstone_green/description.html
  mesecons_lightstone/doc/lightstone_lightgrey/description.html
  mesecons_lightstone/doc/lightstone_red/description.html
  mesecons_lightstone/doc/lightstone_yellow/description.html
  mesecons_luacontroller/doc/luacontroller/description.html
  mesecons_movestones/doc/movestone/description.html
  mesecons_movestones/doc/movestone_sticky/description.html
  mesecons_pistons/doc/piston/description.html
  mesecons_pistons/doc/piston_sticky/description.html
  mesecons_powerplant/doc/powerplant/description.html
  mesecons_random/doc/ghoststone/description.html
  mesecons_random/doc/removestone/description.html
  mesecons_solarpanel/doc/solarpanel/description.html
  mesecons_torch/doc/torch/description.html
  mesecons_wires/doc/mesecon/description.html
Labels: documentation

#449 Luacontroller nodetimer
  mesecons_luacontroller/init.lua
  settingtypes.txt
Labels: enhancement
