Repository minetest-mods/mesecons, pull requests merged in 2018-07, with the labels that each got.

#401 Add missing sound effects and fix wrong pressure plate sounds
  mesecons_delayer/init.lua
  mesecons_extrawires/corner.lua
  mesecons_extrawires/crossover.lua
  mesecons_extrawires/tjunction.lua
  mesecons_extrawires/vertical.lua
  mesecons_hydroturbine/init.lua
  mesecons_insulated/init.lua
  mesecons_pistons/init.lua
  mesecons_pressureplates/init.lua
  mesecons_receiver/init.lua
  mesecons_torch/init.lua
  mesecons_wires/init.lua
Labels: enhancement

#418 Fix crash when error()ing an invalid value
  mesecons_luacontroller/init.lua
Labels: bugfix, trivial

#419 Fix mesecon receiver duplication.
  mesecons_receiver/init.lua
Labels: bugfix

#420 Microcontroller: Check protection access, fix globals assignment
  mesecons_microcontroller/init.lua
Labels: bugfix

#350 Add 'settingtypes.txt'
  settingtypes.txt
Labels: documentation, enhancement, improvement needed
