Repository minetest-mods/mesecons, pull requests merged in 2023-06, with the labels that each got.

#632 Pressure plates check for entity contact
  mesecons_pressureplates/init.lua
Labels: bugfix

#545 Mvps: make mvps stoppers non-replaceable even if they are buildable_to
  mesecons_mvps/init.lua
Labels: high-priority, bugfix

#500 Add string.split function
  mesecons_luacontroller/init.lua
Labels: enhancement
